// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func AuthLayout(title string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Head(title).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</html><body><div class=\"h-screen w-screen flex flex-col md:flex-row justify-center items-center\"><div class=\"grow bg-white\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"h-screen relative overflow-hidden md:flex w-1/2 bg-gradient-to-tr from-blue-800 to-purple-700 i justify-around items-center hidden\"><div class=\"w-full md:w-11/12 lg:w-9/12\"><h2 class=\"text-white font-semibold text-4xl font-montserrat\">GoTask</h2><h1 class=\"text-gray-50 font-bold text-lg md:text-3xl lg:text-5xl mt-4\">The most popular <br>task management <br>System.</h1><p class=\"text-white mt-2\">Millions of designers and developers around the world manage their work on GoTask.</p><div class=\"mt-2 flex align-center justify-between w-96\"><div class=\"flex -space-x-4 rtl:space-x-reverse\"><img class=\"w-8 h-8 border-2 border-white rounded-full dark:border-gray-800\" src=\"https://randomuser.me/api/portraits/thumb/men/39.jpg\" alt=\"\"> <img class=\"w-8 h-8 border-2 border-white rounded-full dark:border-gray-800\" src=\"https://randomuser.me/api/portraits/thumb/women/39.jpg\" alt=\"\"> <img class=\"w-8 h-8 border-2 border-white rounded-full dark:border-gray-800\" src=\"https://randomuser.me/api/portraits/thumb/women/38.jpg\" alt=\"\"></div><span class=\"text-white opacity-40\">|</span><p class=\"text-white font-montserrat\">Over <strong>1.5k+</strong>&nbsp;Happy Customers</p></div></div><div class=\"absolute -bottom-32 -left-40 w-80 h-80 border-4 rounded-full border-opacity-10 border-t-8 border-indigo-400\"></div><div class=\"absolute -bottom-40 -left-20 w-80 h-80 border-4 rounded-full border-opacity-20 border-t-8 border-indigo-400\"></div><div class=\"absolute -top-40 -right-0 w-80 h-80 border-4 rounded-full border-opacity-10 border-t-8 border-indigo-400\"></div><div class=\"absolute -top-20 -right-20 w-80 h-80 border-4 rounded-full border-opacity-20 border-t-8 border-indigo-400\"></div></div></div><script src=\"./static/index.js\"></script></body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func Head(title string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/layouts/auth.templ`, Line: 41, Col: 21}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</title><link rel=\"stylesheet\" href=\"./static/base.css\"></head>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
