name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build cmd/web/*.go
    
    - name: Deploy to DigitalOcean
      env:
        DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}
        DO_HOST: ${{ secrets.DO_HOST }}
        DO_USER: ${{ secrets.DO_USER }}
      run: |
        echo "$DO_SSH_KEY" > do_ssh_key
        chmod 600 do_ssh_key
        scp -i do_ssh_key -o StrictHostKeyChecking=no main $DO_USER@$DO_HOST:~/main
        ssh -i do_ssh_key -o StrictHostKeyChecking=no $DO_USER@$DO_HOST '
          sudo systemctl stop myapp || true
          sudo mv ~/main /usr/local/bin/
          sudo tee /etc/systemd/system/myapp.service << EOF
          [Unit]
          Description=GoTask app
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/main
          Restart=always
          User=root
          Environment=PORT=8080

          [Install]
          WantedBy=multi-user.target
          EOF
          sudo systemctl daemon-reload
          sudo systemctl enable myapp
          sudo systemctl start myapp
        '
