name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Built assets
      run: |
        bun install
        bun run dev

    - name: Build
      run: go build cmd/web/*.go
    
    - name: Deploy to DigitalOcean
      env:
        DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}
        DO_HOST: ${{ secrets.DO_HOST }}
        DO_USER: ${{ secrets.DO_USER }}
      run: |
        echo "$DO_SSH_KEY" > do_ssh_key
        chmod 600 do_ssh_key
        scp -i do_ssh_key -o StrictHostKeyChecking=no main $DO_USER@$DO_HOST:~/main
        ssh -i do_ssh_key -o StrictHostKeyChecking=no $DO_USER@$DO_HOST '
          sudo systemctl stop myapp || true
          sudo mv ~/main /usr/local/bin/
          sudo systemctl daemon-reload
          sudo systemctl enable myapp
          sudo systemctl start myapp
        '
